### ISSUE TITLE
auto: error saving file to elastic

### ISSUE THREAD

**Issue by samthomson** [samthomson/picili#364]
```
production.DEBUG: array (
  0 => '\\nunexpected exception saving file\\n\\nErrorException: Undefined variable: oPiciliFile in /var/www/picili-shared/SharedLibrary/ElasticHelper.php:208
Stack trace:
#0 /var/www/picili-shared/SharedLibrary/ElasticHelper.php(208): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, \'Undefined varia...\', \'/var/www/picili...\', 208, Array)
#1 /var/www/auto/app/Providers/EventServiceProvider.php(37): SharedLibrary\\ElasticHelper::bSaveFileToElastic(NULL)
#2 /var/www/auto/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(348): App\\Providers\\EventServiceProvider->App\\Providers\\{closure}(Object(Share\\PiciliFile))
#3 /var/www/auto/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(199): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}(\'eloquent.saved:...\', Array)
#4 /var/www/auto/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(172): Illuminate\\Events\\Dispatcher->dispatch(\'eloquent.saved:...\', Array, false)
#5 /var/www/auto/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php(148): Illuminate\\Events\\Dispatcher->fire(\'eloquent.saved:...\', Object(Share\\PiciliFile))
#6 /var/www/auto/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(558): Illuminate\\Database\\Eloquent\\Model->fireModelEvent(\'saved\', false)
#7 /var/www/auto/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(529): Illuminate\\Database\\Eloquent\\Model->finishSave(Array)
#8 /var/www/picili-shared/Models/PiciliFile.php(54): Illuminate\\Database\\Eloquent\\Model->save(Array)
#9 /var/www/auto/app/Library/PiciliProcessor.php(557): Share\\PiciliFile->save()
#10 /var/www/auto/app/Library/PiciliProcessor.php(142): App\\Library\\PiciliProcessor::mGeocode(\'959\')
#11 /var/www/auto/app/Console/Commands/ProcessAll.php(54): App\\Library\\PiciliProcessor::bProcessQueue()
#12 [internal function]: App\\Console\\Commands\\ProcessAll->handle()
#13 /var/www/auto/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#14 /var/www/auto/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#15 /var/www/auto/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#16 /var/www/auto/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#17 /var/www/auto/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\\Container\\Container->call(Array)
#18 /var/www/auto/vendor/symfony/console/Command/Command.php(264): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#19 /var/www/auto/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#20 /var/www/auto/vendor/symfony/console/Application.php(888): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /var/www/auto/vendor/symfony/console/Application.php(224): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\ProcessAll), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 /var/www/auto/vendor/symfony/console/Application.php(125): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 /var/www/auto/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 /var/www/auto/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 {main}',
  1 => 'ErrorException',
)  
```

**Comment by samthomson** [comment]
closed by https://github.com/samthomson/picili/commit/68a296e273562080caf2f99907a420fba7f29869
